apiVersion: myelin.io/v1alpha1
kind: Axon
metadata:
  name: rec-rf-demo
spec:

  serviceAccountName: myelin-app-myelin

  artifacts:
    - name: rec-source
      path: /src
      git:
        repo: https://github.com/myelinio/myelin-examples.git
        revision: master

  volumeClaimTemplate:
    metadata:
      name: axon-store
    spec:
      storageClassName: nfs
      accessModes: ["ReadWriteMany"]
      resources:
        requests:
          storage: 1Gi

  tasks:

    - name: DataPrepMyelinRecommender
      container:
        imageBuild:
          repositoryName: preprocess-rf-myelin-recommender
          artifact: rec-source
          buildLocation: /src/recommender-rf-demo
          dockerfile:
            path: Dockerfile.preprocess


    - name: TrainMyelinRecommender
      train:
        imageBuild:
          repositoryName: train-rf-myelin-recommender
          artifact: rec-source
          buildLocation: /src/recommender-rf-demo
          dockerfile:
            path: Dockerfile.train

    - name: DeployMyelinRecommender
      deploy:
        endpointType: REST
        endpointRestType: Multipart
        imageBuild:
          repositoryName: deploy-rf-myelin-recommender
          artifact: rec-source
          buildLocation: /src/
          s2i:
            contextDir: recommender-rf-demo
            builderImage: docker.io/myelinio/myelin-deployer-s2i-py3:v0.1.5

  sensors:

    - name: TrainOnStart
      tasks:
        - resourceExecutor:
            task: DataPrepMyelinRecommender
        - trainer:
            task: TrainMyelinRecommender


    - name: DeploymentDecisionMaker
      triggers:
        - name: mnistTrainingComplete
          type: Lifecycle
          condition: Succeeded
          task: TrainMyelinRecommender

      tasks:
        - deployer:
            name: modeldeployer
            rolloutSpec:
              - destinations:
                  - destinationIndex: 0
                    weight: 50
                  - destinationIndex: 1
                    weight: 50
            replicas: 1
            models:
              - name: MyelinRFRecommender
                modelSelectionStrategy: "best"
                routingStrategy:
                  - destinations:
                      - destinationName: backend-recommender
                        weight: 100
                backendModels:
                  - name: backend-recommender
                    trainer: TrainMyelinRecommender
                    deployer: DeployMyelinRecommender
                    modelSelectionStrategy: "best"
            routes:
              - path: /predict
                dag:
                  - model: MyelinRFRecommender
                    path: /predict
              - path: /send-feedback
                dag:
                  - model: MyelinRFRecommender
                    path: /send-feedback

    - name: PostDeploymentDecisionMaker
      triggers:
        - name: RecommenderDeployAccuracy
          type: Alert
          condition: "{{recommender_deploy_accuracy}} < 0.90"
      tasks:
        - resourceExecutor:
            task: DataPrepMyelinRecommender
        - trainer:
            task: TrainMyelinRecommender
