apiVersion: myelinproj.io/v1alpha1
kind: Axon
metadata:
  name: two-stage-vae
spec:

  serviceAccountName: myelin-app-myelin

  artifacts:
    - name: rec-source
      path: /src
      git:
        repo: https://github.com/myelinio/myelin-examples.git
        revision: master

  volumeClaimTemplate:
    metadata:
      name: axon-store
    spec:
      storageClassName: nfs
      accessModes: ["ReadWriteMany"]
      resources:
        requests:
          storage: 1Gi

  tasks:

    - name: DataPrep
      container:
        image: myelinio/two-stage-vae-train-cpu:v0.1.0

    - name: Train
      train:
        image: myelinio/two-stage-vae-train-cpu:v0.1.4
        lossMetric: "fid_gen2"
        lossMetricSelector: greater
        hpTuning:
          concurrency: 1
          minBudget: 3
          maxBudget: 10
          numIteration: 1
          optimiser: BOHB
          params:
            - type: UniformInteger
              name: second-dim
              numerical:
                lower: "128"
                upper: "2048"
                default_value: "1024"
                log: true

  sensors:
    - name: TrainOnStart
      tasks:
        - resourceExecutor:
            task: DataPrep
        - trainer:
            task: Train