# docker build -t myelinio/advanced-east:v0.1.0 -f Dockerfile.train .
# docker run myelinio/advanced-east:v0.1.0
FROM tensorflow/tensorflow:1.13.1-py3

RUN pip3 install --upgrade pip

WORKDIR /app

COPY requirements-train.txt requirements.txt
RUN for req in $(cat requirements.txt); do pip install $req; done


COPY . /app


ENTRYPOINT ["python", "advanced_east.py"]