apiVersion: myelinproj.io/v1alpha1
kind: Axon
metadata:
  name: pi-spark
spec:
  serviceAccountName: myelin-app-myelin
  artifacts:
    - name: spark-job-source
      path: /src
      git:
        repo: https://github.com/myelinio/myelin-examples.git
        revision: master
  volume:
    name: spark-job-axon-store
    hostPath:
      path: /var/lib/myelin
  tasks:
    - name: SparkTask
      spark:
        image: docker.io/myelinio/spark-client:v2.3.0
        sparkSpec:
          properties: |
            spark.kubernetes.container.image docker.io/myelinio/spark-client:v2.3.0-k8s-1.14-1
            spark.driver.cores 0.1
            spark.executor.instances 4
            spark.executor.cores 1
            spark.executor.memory 512m
            spark.driver.memory 1024m

          class: spark.pi.SparkPi
          jars:
            - http://central.maven.org/maven2/com/databricks/spark-avro_2.11/4.0.0/spark-avro_2.11-4.0.0.jar
            - gs://myelin-development-spark-on-k8s2/jars/pi-example-1.0-SNAPSHOT-jar-with-dependencies.jar
  sensors:
    - name: SparkTask
      tasks:
        - resourceExecutor:
            task: SparkTask
