FROM python:3.6-slim

COPY requirements.txt requirements.txt
RUN pip install -r  requirements.txt

WORKDIR /work

COPY ./model.py /work/model.py
COPY ./predict_rest.py /work/predict_rest.py

CMD python predict_rest.py
