FROM python:3.6


RUN pip3 install --upgrade pip

COPY requirements.txt requirements.txt
RUN pip install -r  requirements.txt

WORKDIR /work

COPY ./train.py /work/train_hp.py

CMD python train_hp.py
