# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ocr_recognition_pb2 as ocr__recognition__pb2


class OcrRecognitionServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.RecogniseText = channel.unary_unary(
        '/OcrRecognitionService/RecogniseText',
        request_serializer=ocr__recognition__pb2.RecognitionRequest.SerializeToString,
        response_deserializer=ocr__recognition__pb2.RecognitionReply.FromString,
        )


class OcrRecognitionServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def RecogniseText(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_OcrRecognitionServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'RecogniseText': grpc.unary_unary_rpc_method_handler(
          servicer.RecogniseText,
          request_deserializer=ocr__recognition__pb2.RecognitionRequest.FromString,
          response_serializer=ocr__recognition__pb2.RecognitionReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'OcrRecognitionService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
