# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ocr-recognition.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ocr_common_pb2 as ocr__common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ocr-recognition.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15ocr-recognition.proto\x1a\x10ocr-common.proto\"9\n\x12RecognitionRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x15\n\x05image\x18\x02 \x01(\x0b\x32\x06.Image\"!\n\x10RecognitionReply\x12\r\n\x05label\x18\x01 \x01(\t2R\n\x15OcrRecognitionService\x12\x39\n\rRecogniseText\x12\x13.RecognitionRequest\x1a\x11.RecognitionReply\"\x00\x62\x06proto3')
  ,
  dependencies=[ocr__common__pb2.DESCRIPTOR,])




_RECOGNITIONREQUEST = _descriptor.Descriptor(
  name='RecognitionRequest',
  full_name='RecognitionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='RecognitionRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image', full_name='RecognitionRequest.image', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=100,
)


_RECOGNITIONREPLY = _descriptor.Descriptor(
  name='RecognitionReply',
  full_name='RecognitionReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='label', full_name='RecognitionReply.label', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=135,
)

_RECOGNITIONREQUEST.fields_by_name['image'].message_type = ocr__common__pb2._IMAGE
DESCRIPTOR.message_types_by_name['RecognitionRequest'] = _RECOGNITIONREQUEST
DESCRIPTOR.message_types_by_name['RecognitionReply'] = _RECOGNITIONREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecognitionRequest = _reflection.GeneratedProtocolMessageType('RecognitionRequest', (_message.Message,), dict(
  DESCRIPTOR = _RECOGNITIONREQUEST,
  __module__ = 'ocr_recognition_pb2'
  # @@protoc_insertion_point(class_scope:RecognitionRequest)
  ))
_sym_db.RegisterMessage(RecognitionRequest)

RecognitionReply = _reflection.GeneratedProtocolMessageType('RecognitionReply', (_message.Message,), dict(
  DESCRIPTOR = _RECOGNITIONREPLY,
  __module__ = 'ocr_recognition_pb2'
  # @@protoc_insertion_point(class_scope:RecognitionReply)
  ))
_sym_db.RegisterMessage(RecognitionReply)



_OCRRECOGNITIONSERVICE = _descriptor.ServiceDescriptor(
  name='OcrRecognitionService',
  full_name='OcrRecognitionService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=137,
  serialized_end=219,
  methods=[
  _descriptor.MethodDescriptor(
    name='RecogniseText',
    full_name='OcrRecognitionService.RecogniseText',
    index=0,
    containing_service=None,
    input_type=_RECOGNITIONREQUEST,
    output_type=_RECOGNITIONREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_OCRRECOGNITIONSERVICE)

DESCRIPTOR.services_by_name['OcrRecognitionService'] = _OCRRECOGNITIONSERVICE

# @@protoc_insertion_point(module_scope)
