apiVersion: myelinproj.io/v1alpha1
kind: Axon
metadata:
  name: ml-gpt2-gpu
spec:

  serviceAccountName: myelin-app-myelin

  artifacts:
    - name: gpt2-source
      path: /src
      git:
        repo: https://github.com/myelinio/myelin-examples.git
        revision: master

  volumeClaimTemplate:
    metadata:
      name: axon-store
    spec:
      storageClassName: nfs
      accessModes: ["ReadWriteMany"]
      resources:
        requests:
          storage: 1Gi

  tasks:

    - name: DataPrepGPT2
      container:
        imageBuild:
          repositoryName: preprocess-myelin-gpt2
          artifact: gpt2-source
          buildLocation: /src/gpt2_demo
          dockerfile:
            path: Dockerfile.preprocess


    - name: TrainGPT2
      train:
        imageBuild:
          repositoryName: train-myelin-gpt2
          artifact: gpt2-source
          buildLocation: /src/gpt2_demo
          dockerfile:
            path: Dockerfile.train-gpu
        env:
          - name: LD_LIBRARY_PATH
            value: /usr/local/nvidia/lib64:/usr/local/nvidia/bin
        nodeSelector:
          cloud.google.com/gke-accelerator: "nvidia-tesla-p4"
        resources:
          limits:
            nvidia.com/gpu: 1

    - name: DeployGPT2
      deploy:
        endpointType: REST
        endpointRestType: Multipart
        imageBuild:
          repositoryName: deploy-myelin-gpt2
          artifact: gpt2-source
          buildLocation: /src/
          s2i:
            contextDir: gpt2_demo
            builderImage: docker.io/myelinio/myelin-deployer-s2i-cuda10-runtime-py3:v0.1.6
        env:
          - name: LD_LIBRARY_PATH
            value: /usr/local/nvidia/lib64:/usr/local/nvidia/bin
        nodeSelector:
          cloud.google.com/gke-accelerator: "nvidia-tesla-p4"
        resources:
          limits:
            nvidia.com/gpu: 1

  sensors:

    - name: TrainOnStart
      tasks:
        - resourceExecutor:
            task: DataPrepGPT2
        - trainer:
            task: TrainGPT2


    - name: DeploymentDecisionMaker
      triggers:
        - name: trainComplete
          type: Lifecycle
          condition: Succeeded
          task: TrainGPT2

      tasks:
        - deployer:
            name: deployer1
            rolloutSpec:
              - destinations:
                  - destinationIndex: 0
                    weight: 100
            models:
              - name: MyelinGPT2
                modelSelectionStrategy: "best"
                routingStrategy:
                  - destinations:
                      - destinationName: shakespearegp2
                        weight: 100
                backendModels:
                  - name: shakespearegp2
                    trainer: TrainGPT2
                    deployer: DeployGPT2
                    modelSelectionStrategy: "best"
            routes:
              - path: /predict
                dag:
                  - model: MyelinGPT2
                    path: /predict
              - path: /send-feedback
                dag:
                  - model: MyelinGPT2
                    path: /send-feedback
