# docker build -t myelinio/two-stage-vae-preprocess:v0.1.0 -f Dockerfile.preprocess .
# docker run  myelinio/two-stage-vae-preprocess:v0.1.0
FROM tensorflow/tensorflow:1.13.1-gpu-py3

RUN pip3 install --upgrade pip

WORKDIR /app

COPY requirements-preprocess.txt requirements.txt
RUN for req in $(cat requirements.txt); do pip install $req; done


COPY . /app


ENTRYPOINT ["python", "preprocess.py"]