
apiVersion: myelinproj.io/v1alpha1
kind: Axon
metadata:
  name: github-insights-spark
spec:
  serviceAccountName: myelin-app-myelin
  artifacts:
    - name: spark-job-source
      path: /src
      git:
        repo: https://github.com/myelinio/myelin-examples.git
        revision: master
  volume:
    name: spark-job-axon-store
    hostPath:
      path: /var/lib/myelin
  tasks:
    - name: SparkTask
      spark:
        imageBuild:
          repositoryName: github-insights-spark
          artifact: spark-job-source
          buildLocation: /src/github-insights-spark/
          dockerfile:
            path: Dockerfile
          volumeMounts:
            - name: google-cloud-key
              mountPath: /src/github-insights-spark/secrets
          volumes:
            - name: google-cloud-key
              secret:
                secretName: spark-sa
        sparkSpec:
          properties: |
            spark.kubernetes.driverEnv.GCS_PROJECT_ID myelin-development
            spark.kubernetes.driverEnv.GOOGLE_APPLICATION_CREDENTIALS /mnt/secrets/spark-sa.json
            spark.kubernetes.container.image docker.io/myelinio/spark-client:v2.3.0-k8s-1.14-1
            spark.kubernetes.driver.secrets.spark-sa  /mnt/secrets
            spark.kubernetes.executor.secrets.spark-sa /mnt/secrets
            spark.kubernetes.authenticate.driver.serviceAccountName	spark
            spark.driver.cores 0.1
            spark.executor.instances 2
            spark.executor.cores 1
            spark.executor.memory 512m
            spark.driver.memory 1024m
            spark.executorEnv.GCS_PROJECT_ID    myelin-development
            spark.executorEnv.GOOGLE_APPLICATION_CREDENTIALS /mnt/secrets/spark-sa.json
            spark.hadoop.google.cloud.auth.service.account.enable true
            spark.hadoop.google.cloud.auth.service.account.json.keyfile /mnt/secrets/spark-sa.json
            spark.hadoop.fs.gs.project.id myelin-development
            spark.hadoop.fs.gs.system.bucket myelin-development-spark-on-k8s2
            spark.dynamicAllocation.executorIdleTimeout 600s

          # OR a config map
          #        propertiesConfigMap: spark-config
          #        propertiesConfigMapKey: spark-properties
          # DEFAULT cluster
          #        deployMode: cluster
          class: spark.bigquery.example.github.NeedingHelpGoPackageFinder
          jars:
            - http://central.maven.org/maven2/com/databricks/spark-avro_2.11/4.0.0/spark-avro_2.11-4.0.0.jar
            - gs://myelin-development-spark-on-k8s2/jars/github-insights-1.0-SNAPSHOT-jar-with-dependencies.jar
          args:
            - myelin-development
            - spark_on_k8s
            - myelin-development-spark-on-k8s2
            - --usesample
  sensors:
    - name: SparkTask
      tasks:
        - resourceExecutor:
            task: SparkTask