# docker build -t myelinio/advanced-east-preprocess:v0.1.0 -f Dockerfile.preprocess .
# docker run -v /Users/ryadhkhsib/Dev/workspaces/nn/myelin-examples/ocr/detection/AdvancedEAST/icpr:/data/icpr myelinio/advanced-east-preprocess:v0.1.0
FROM python:3.6

RUN pip3 install --upgrade pip

WORKDIR /app

COPY requirements-preprocess.txt requirements.txt
RUN for req in $(cat requirements.txt); do pip install $req; done


COPY . /app


ENTRYPOINT ["./preprocess.sh"]