FROM python:3.6

RUN pip3 install --upgrade pip

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

WORKDIR /work

RUN mkdir /work/image_classifier/

COPY train-tf.py /work/image_classifier/train-tf.py

CMD python image_classifier/train-tf.py