apiVersion: myelinproj.io/v1alpha1
kind: Axon
metadata:
  name: mnist-tfjob
spec:

  serviceAccountName: myelin-app-myelin

  artifacts:
    - name: rec-source
      path: /src
      git:
        repo: git@github.com:myelinio/myelin-examples.git
        revision: master
        sshPrivateKeySecret:
          name: github-creds
          key: ssh-private-key

  volumeClaimTemplate:
    metadata:
      name: axon-store1
    spec:
      storageClassName: nfs
      accessModes: ["ReadWriteMany"]
      resources:
        requests:
          storage: 1Gi

  tasks:

    - name: TfJob
      train:
        imageBuild:
          repositoryName: train-myelin-test
          artifact: rec-source
          buildLocation: /src/mnist_with_summaries
          dockerfile:
            path: Dockerfile
#        image: myelinio/tf-dist-mnist-test:1.0
        tfJobSpec:
          tfReplicaSpecs:
            PS:
              replicas: 2
              restartPolicy: Never
              template:
                spec:
                  containers:
                    - name: tensorflow
            Worker:
              replicas: 4
              restartPolicy: Never
              template:
                spec:
                  containers:
                    - name: tensorflow
        metrics:
          - name: test_accuracy
            type: Gauge


  sensors:

    - name: TfJobTrain
      tasks:
        - resourceExecutor:
            task: TfJob
