FROM tensorflow/tensorflow:1.11.0-devel-gpu

WORKDIR /app/ctpn/

ADD ./requirements.txt /app/ctpn/requirements.txt
RUN pip install -r requirements.txt

RUN apt update && apt install -y libsm6 libxext6  libxrender-dev

ADD . /app/ctpn/
RUN sh ./setup.sh

VOLUME ["/app/ctpn/test_images", "/app/ctpn/test_result"]

CMD python train.py
