# docker build -t myelinio/ctpn-train:v0.1.0 -f Dockerfile.train
FROM tensorflow/tensorflow:1.11.0-devel-gpu

WORKDIR /app/ctpn/

ADD ./requirements.txt /app/ctpn/requirements.txt
RUN pip install -r requirements.txt

RUN apt update && apt install -y libsm6 libxext6  libxrender-dev

ADD . /app/ctpn/
RUN sh ./setup.sh

VOLUME ["/app/ctpn/data/VOCdevkit2007/VOC2007", "/app/ctpn/output"]

EXPOSE 6006

CMD python ./ctpn/train_net.py

